/**
 * @module middlewares/setLocals
 * @description Middleware that sets authentication status, user data, and CSRF token to `res.locals`.
 * 
 * This middleware is responsible for setting the following local variables in the response object:
 * - `isAuthenticated`: A boolean indicating if the user is logged in, based on the session.
 * - `user`: The authenticated user's data, retrieved from the `req.user` object.
 * - `csrfToken`: The CSRF token, which is generated by the `req.csrfToken()` method, if available.
 * 
 * These local variables can then be used in the views (e.g., in EJS templates) to customize the UI based on the user's authentication status or to include the CSRF token in forms.
 * 
 * @param {Object} req - The request object containing the incoming HTTP request. It may include session and user data.
 * @param {Object} res - The response object used to send a response back to the client. This middleware sets local variables on it.
 * @param {Function} next - The next middleware function to call after the current one completes.
 * 
 * @returns {void} - This function does not return anything but modifies the response object for use in views.
 * 
 * @example
 * // Usage example:
 * app.use(setLocals);
 * 
 */
module.exports = (req, res, next) => {
  res.locals.isAuthenticated = req.session.isLoggedIn;  // Set the authentication status
  res.locals.user = req.user;                           // Set the user data if available

  if (req.csrfToken) {                                  // Set the CSRF token if available
    res.locals.csrfToken = req.csrfToken();
  }

  next();                                               // Proceed to the next middleware
};

