const mongoose = require("mongoose");
/**
 * The Reservation schema represents a reservation in the system.
 * 
 * @module models/reservations
 * @model Reservations
 * @description This model stores the details of a reservation including the catway number, client name, boat name, check-in date, and check-out date.
 */

/**
 * @typedef {Object} Reservation
 * @property {number} catwayNumber - The reserved catway number.
 * @property {string} clientName - The name of the client who made the reservation.
 * @property {string} boatName - The name of the boat being reserved.
 * @property {Date} checkIn - The check-in date of the reservation.
 * @property {Date} checkOut - The check-out date of the reservation.
 * @property {Date} createdAt - The creation date of the reservation (automatically generated by Mongoose).
 * @property {Date} updatedAt - The last update date of the reservation (automatically generated by Mongoose).
 */

/**
 * Schema for the Reservation model.
 * 
 * @type {mongoose.Schema<Reservation>}
 */
const reservationSchema = new mongoose.Schema(
  {
    /**
     * The reserved catway number.
     * @type {number}
     * @required
     */
    catwayNumber: { 
      type: Number, 
      required: true 
    },

    /**
     * The name of the client who made the reservation.
     * @type {string}
     * @required
     */
    clientName: { 
      type: String,
      required: true
    },

    /**
     * The name of the boat being reserved.
     * @type {string}
     * @required
     */
    boatName: { 
      type: String, 
      required: true 
    },

    /**
     * The check-in date of the reservation.
     * @type {Date}
     * @required
     */
    checkIn: {
      type: Date, 
      required: true 
    },

    /**
     * The check-out date of the reservation.
     * @type {Date}
     * @required
     */
    checkOut: {
      type: Date, 
      required: true 
    } 
  },
  {
    timestamps: true // Automatically adds createdAt and updatedAt fields
  }
);

/**
 * Model for the catway reservation.
 * 
 * @type {mongoose.Model<Reservation>}
 */
module.exports = mongoose.model("Reservation", reservationSchema);

